#!/bin/bash

set -euo pipefail

MY="$(dirname "$(realpath "$0")")"

BIN="$("$MY/detex-build")"

T="$(realpath "$(mktemp -d)")"
finish() {
    cd /
    rm -rf "$T"
}
trap finish EXIT

if [ -n "${DISPLAY:-}" ] && command -v xclip >/dev/null; then
    xclip -selection clipboard -out | "$MY/detex-util" diffy >"$T/new.txt"
else
    "$MY/detex-util" diffy >"$T/new.txt"
fi

"$BIN" -lsr1 "$@" | "$MY/detex-util" canon | "$MY/detex-util" diffy >"$T/old.txt"
git -c diff.default.xfuncname="^%%%%%%%% .* %%%%%%%%$" diff --no-index -w --word-diff -- "$T/old.txt" "$T/new.txt"
