#!/bin/bash

set -euo pipefail

if [ "$#" -eq 1 ]; then
    case "$1" in
        -v|--version|-V|version)
            echo 'OpenDetex version @VERSION@'
            echo 'https://github.com/b1f6c1c4/opendetex'
            exit
            ;;
    esac
fi

MY="$(dirname "$(realpath "$0")")"

SRC=/usr/share/opendetex
DIR=/var/cache/opendetex

if ! [ -r .detexrc ]; then
    echo "$MY/detex-default"
    exit
fi

if [ ! -d "$DIR" ] || [ ! -w "$DIR" ]; then
    echo "Warning: $DIR is not a writable directory" >&2
    echo "$MY/detex-default"
    exit
fi

DIR="$DIR/$(whoami)"
mkdir -p "$DIR"
chmod 700 "$DIR"

if ! [ -x "$SRC" ]; then
    echo "Warning: $SRC is not searchable" >&2
    echo "$MY/detex-default"
    exit
fi

SHA="$(sha1sum .detexrc | cut -d ' ' -f 1)"
BIN="$DIR/$SHA"
if [ ! -x "$BIN" ] || [ "$0" -nt "$BIN" ] || [ "$SRC/detex-2.l" -nt "$BIN" ] || [ "$SRC/detex-1.l" -nt "$BIN" ]; then
    echo "Notice: Compiling $BIN from $PWD/.detexrc" >&2
    cat "$SRC/detex-1.l" .detexrc "$SRC/detex-2.l" \
        | flex -o /dev/stdout \
        | gcc -std=c2x -march=native -Wall -Wextra -Werror -pedantic -I "$SRC" -O3 -lfl -o "$BIN" -x c -DVERSION=\"@VERSION@-$SHA\" -
fi
echo "$BIN"
